
OBJS = \
	Main.o			\
	PlugExternal.o		\
	PlugNameSpace.o		\
	
Program			= plug.library

TARGETS			= aros os3 morphos os4
OBJDIRS			= 
MAKEDIRS		= 

BUILD_LIBRARY		= 0

INCOPTS			= 
LIBOPTS			= -lGeneric -lLibrary -lC 

OWNSTARTUP		= 1
AROS_LIBOPTS		= 
M68K_LIBOPTS		=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

	include ../Generic/Makefile.mk
