
OBJS = \
	Plug.o							\
	Globals.o						\
	GUI.o							\
	MUIPageSelect.o					\
	MUITracksDataAudio.o			\
	MUIMedia.o						\
	MUIContents.o					\
	MUIDrive.o						\
	MUISettings.o					\
	MUIRecord.o						\
	MUIDriveSelect.o				\
	MUISpeedSelect.o				\
	MUIPopDevice.o					\
	MUIPopDOSDevice.o				\
	MUIPopUnit.o					\
	MUICommon.o						\
	MUIPopAction.o					\
	Components/MUIToolBar.o
	
Program			= gui.plugin

TARGETS			= aros os3 morphos os4
OBJDIRS			= Components
MAKEDIRS		= 

BUILD_LIBRARY	= 0

INCOPTS			= 
LIBOPTS			= -lLibrary -lGeneric -lC

OWNSTARTUP		= 1
AROS_LIBOPTS	= 
M68K_LIBOPTS	=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

	include ../../Generic/Makefile.mk

// vim: noet ts=4
# DO NOT DELETE
