
OBJS = \
	Plug.o				\
	Main.o 				\
	Various.o               	\
	Drive.o    			\
	DriveIO.o			\
	DriveMsg.o			\
	DriveSpool.o			\
	Commands.o              	\
	Pages.o				\
	Disc_CD_ROM.o 			\
	Disc_CD_R.o			\
	Disc_CD_RW.o			\
   	Disc_DVD_ROM.o			\
   	Disc_DVD_PlusR.o		\
   	Disc_DVD_PlusRW.o		\
   	Disc_DVD_MinusR.o		\
   	Disc_DVD_MinusRW.o		\
   	Disc_DVD_RAM.o          	\
   	Disc_Generic.o          	\
	Disc_BD_ROM.o			\
	Disc_BD_R.o			\
	DriveClient.o			\
   	TOC_Elements.o          	\
   	Humming.o			\
	Config.o			\
	CfgVendors.o			\
	CfgIOCodes.o			\
	CfgDrivers.o			\
	CfgHardware.o			\
	CfgCDInfo.o			\
	CfgIOMeas.o			\
	OptItem.o			\
	OptSession.o			\
	OptDisc.o			\
	OptTrack.o			\
	OptIndex.o			\
	CDText.o			\
	SCSI/SCSICommand.o		\
	SCSI/scsi_DiscStructure.o	\
	SCSI/scsi_GetConfiguration.o	\
	SCSI/scsi_Format.o		\
	SCSI/scsi_GetPerformance.o

   	
Program			= optical.plugin

TARGETS			= aros os3 morphos os4
OBJDIRS			= SCSI

INCOPTS			= 
LIBOPTS			= -lGeneric -lC -lLibrary

OWNSTARTUP		= 1
AROS_LIBOPTS	= 
M68K_LIBOPTS	=
MOS_LIBOPTS		=
OS4_LIBOPTS		=

BUILD_LIBRARY	= 0

	include ../Generic/Makefile.mk
# DO NOT DELETE
